// Copies the Nimiq icons NimFind uses from the MIT licensed `nimiq-icons` set into a small module.
// Run with: node scripts/gen-icons.mjs
import { readFileSync, writeFileSync } from "node:fs";

const set = JSON.parse(readFileSync(new URL("../node_modules/nimiq-icons/icons.json", import.meta.url), "utf8"));
const names = [
  "shopping-bag", "credit-card", "qr", "plus", "chevron-left", "chevron-right", "check", "cross",
  "copy", "trash", "star", "locked-lock", "info", "alert", "sand-clock", "arrow-to-bottom", "arrow-top-right",
  "world-check", "arrows-to-sides",
];

const icons = {};
for (const name of names) {
  const icon = set.icons[name];
  if (!icon) throw new Error(`Missing icon ${name}`);
  icons[name] = { width: icon.width ?? set.width, height: icon.height ?? set.height, body: icon.body };
}

writeFileSync(
  new URL("../web/src/icons.generated.ts", import.meta.url),
  `// Generated by scripts/gen-icons.mjs from nimiq-icons (MIT). Do not edit by hand.\n` +
    `export const nimiqIcons = ${JSON.stringify(icons, null, 2)} as const;\n`,
);
console.log(`Wrote ${names.length} icons`);
